version: "3.5"

services:

  bahmni-uat:
    - type: bind
      source: /opt/${bahmni_implementation_name}-bahmni-config
      target: /etc/bahmni-installer/deployment-artifacts/${bahmni_implementation_name}_config
      read_only: true
